### ISSUE TITLE
Graph PB File

### ISSUE THREAD

**Issue by samuel-davis** [KranthiGV/Pretrained-Show-and-Tell-model#2]
If possible can you please upload the Graph.pb file associated with this model ? And if not can you tell me how to create it from the checkpoints you have provided ? 

And thank you so much for uploading these !

**Comment by KranthiGV** [comment]
@samuel-davis 
Sure!
I will upload the graph.pbtxt file in a day.
You would be able to generate the .pb file from it, if you need the compressed representation of the graph.

**Comment by KranthiGV** [comment]
Uploaded!
I think [this commit](https://github.com/KranthiGV/Pretrained-Show-and-Tell-model/commit/09085c4be496ea5b0662f605eeba7b1bd4df188e) closes the issue. If there's anything else, feel free to re-open this or open a new issue.

**Comment by samuel-davis** [comment]
Thanks definitely helped me out a ton.

**Comment by KranthiGV** [comment]
I'm glad it did. Let me know if you need anything else!
