### ISSUE TITLE
Request perplexity values

### ISSUE THREAD

**Issue by LEAAN** [KranthiGV/Pretrained-Show-and-Tell-model#4]
Thank you for the checkpoint files!
Could you please also share the perplexity values from evaluation script, if any? Would also appreciate graphs from tensorboard.

**Comment by KranthiGV** [comment]
@LEAAN 
Hello! :smile: 
I haven't run the evaluation script as of now.
I will definitely post the results when I do. I cannot guarantee you any deadline now.
Regarding the graphs, I will post them in a day or two.

**Comment by KranthiGV** [comment]
@LEAAN 
I have uploaded the events file in the `extras/tensorboard` folder. Have a look at it.
I ran the eval script, but I realised I should have run it during the training.
I got perplexity value of **8.440368** at the 2M iteration. Sorry for not being able to help.
Let me know if there's any. I think this can be closed for now. Re-open this issue of open another if there's anything!
