### ISSUE TITLE
 Key lstm/basic_lstm_cell/kernel not found in checkpoint

### ISSUE THREAD

**Issue by DominikFilipiak** [KranthiGV/Pretrained-Show-and-Tell-model#9]
The same issue already opened, sorry.

I had tried to run your model on the latest version of TF (1.2.0), but encountered the following error:
` Key lstm/basic_lstm_cell/kernel not found in checkpoint`
I've found @cshallue [answer](https://github.com/tensorflow/models/issues/466#issuecomment-286953049). The original version didn't work out for me. After some digging, I've changed values in vars_to_rename - did the trick.
```
OLD_CHECKPOINT_FILE = "model.ckpt-1000000"
NEW_CHECKPOINT_FILE = "model2.ckpt-1000000"

import tensorflow as tf
vars_to_rename = {
    "lstm/basic_lstm_cell/weights": "lstm/basic_lstm_cell/kernel",
    "lstm/basic_lstm_cell/biases": "lstm/basic_lstm_cell/bias",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
for old_name in reader.get_variable_to_shape_map():
  if old_name in vars_to_rename:
    new_name = vars_to_rename[old_name]
  else:
    new_name = old_name
  new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
  sess.run(init)
  saver.save(sess, NEW_CHECKPOINT_FILE)
```

One might find it useful.

**Comment by vgavro** [comment]
Simply creating vurtualenv and downgrading tensorflow seems to work too:
```
virtualenv ./env
./env/bin/pip install tensorflow==1.0 werkzeug
source ./env/bin/activate
```

**Comment by rogerpasky** [comment]
If you have an outdated checkpoint file (as I found in Syntaxnet), just use the "official" contributed translator you can find in:
`models/research/syntaxnet/tensorflow/tensorflow/contrib/rnn/python/tools/checkpoint_convert.py`

**Comment by thunfischtoast** [comment]
> 
> 
> If you have an outdated checkpoint file (as I found in Syntaxnet), just use the "official" contributed translator you can find in:
> `models/research/syntaxnet/tensorflow/tensorflow/contrib/rnn/python/tools/checkpoint_convert.py`

I uploaded the converted checkpoint (V2) here: 

https://drive.google.com/file/d/1MN_Az1fF-DFDt0FNt5KFO8Fo0xl2KdVc/view?usp=sharing

This has beed tested with Tensorflow 1.12
